# Generated by Django 4.0 on 2021-12-23 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finweb', '0002_growthdata_profitdata_reportdata_stockdata_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockdata',
            old_name='ii',
            new_name='index',
        ),
    ]
