# Generated by Django 4.0 on 2021-12-23 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finweb', '0003_rename_ii_stockdata_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockdata',
            old_name='index',
            new_name='ii',
        ),
    ]
