# Generated by Django 4.0 on 2022-01-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finweb', '0004_rename_index_stockdata_ii'),
    ]

    operations = [
        migrations.CreateModel(
            name='recommenddata',
            fields=[
                ('index', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('code', models.BigIntegerField(blank=True, null=True)),
                ('sentiment', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'finweb_recommenddata',
                'managed': True,
            },
        ),
    ]
