# Generated by Django 4.0 on 2022-01-02 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finweb', '0005_recommenddata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommenddata',
            old_name='index',
            new_name='ii',
        ),
    ]
